version: '3'
services:
  api.redis:
    image: valkey/valkey:latest
    hostname: api.redis
    container_name: api.redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
    - ${REDIS_PORT}:6379
    volumes:
    - redis_data:/data
    env_file:
    - ./.env
  api.backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - ${APP_PORT}:8000
    env_file:
    - ./.env
  api.postgres:
    image: postgres:latest
    hostname: api.postgres
    container_name: api.postgres
    ports:
    - ${POSTGRES_PORT}:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
    - ./.env
volumes:
  redis_data:
  pgdata:
